// <auto-generated />
namespace ZenchenkoProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WarmFloorUpdate31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WarmFloorUpdate31));
        
        string IMigrationMetadata.Id
        {
            get { return "201609211445587_WarmFloorUpdate31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
