// <auto-generated />
namespace ZenchenkoProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WarmFloorIsInStockAdded2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WarmFloorIsInStockAdded2));
        
        string IMigrationMetadata.Id
        {
            get { return "201609191439338_WarmFloorIsInStockAdded2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
