// <auto-generated />
namespace OnlineShop.Migrations.AuthMigratons
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DateModifiedAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateModifiedAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201608301125158_DateModifiedAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
