// <auto-generated />
namespace OnlineShop.Migrations.OnlineShopDataBase
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangedGoodToGlobalDatabase2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedGoodToGlobalDatabase2));
        
        string IMigrationMetadata.Id
        {
            get { return "201609011654216_ChangedGoodToGlobalDatabase2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
